 
version: '3.1'
services:
  ridesupport_manageservices_ms:
    build: .
    command: python -u /home/ServicesRestApi.py
    ports:
      - "4004:4004"
    
    stdin_open: true
    tty: true
    links:
      - ridesupport_manageservices_db:l_services
  ridesupport_manageservices_db:
    image: "mongo"
    ports:
      - "4003:27017"
